import { TypographyOptions } from '@mui/material/styles/createTypography';

const typography: TypographyOptions = {
    htmlFontSize: 16,
    fontFamily:
        "'open sans', 'Nirmala UI', Roboto, 'helvetica', 'Helvetica Neue', sans-serif, -apple-system, BlinkMacSystemFont, 'Segoe UI', Oxygen-Sans, Ubuntu, Cantarell",
    fontSize: 14,
    fontWeightLight: 300,
    fontWeightRegular: 400,
    fontWeightMedium: 500,
    fontWeightBold: 700,
    h1: {
        fontFamily: 'Fresca, "Roboto", "Helvetica", "Arial", sans-serif',
        fontWeight: 300,
        fontSize: '48px',
        lineHeight: 1.167,
        // letterSpacing: '-0.01562em',
        letterSpacing: '2px',
        textAlign: 'left',
    },
    h2: {
        fontFamily: 'Fresca, "Roboto", "Helvetica", "Arial", sans-serif',
        fontWeight: 300,
        fontSize: '32px',
        lineHeight: 1.2,
        // letterSpacing: '-0.00833em',
        letterSpacing: '2px',
        textAlign: 'left',
    },
    h3: {
        fontFamily: '"Roboto", "Helvetica", "Arial", sans-serif',
        fontWeight: 400,
        fontSize: '26px',
        lineHeight: 1.167,
        letterSpacing: '0em',
        textAlign: 'left',
    },
    h4: {
        fontFamily: '"Roboto", "Helvetica", "Arial", sans-serif',
        fontWeight: 400,
        fontSize: '24px',
        lineHeight: 1.235,
        letterSpacing: '0.00735em',
        textAlign: 'left',
    },
    h5: {
        fontFamily: '"Roboto", "Helvetica", "Arial", sans-serif',
        fontWeight: 400,
        fontSize: '20px',
        lineHeight: 1.334,
        letterSpacing: '0em',
        textAlign: 'left',
    },
    h6: {
        fontFamily: '"Roboto", "Helvetica", "Arial", sans-serif',
        fontWeight: 500,
        fontSize: '18px',
        lineHeight: 1.6,
        letterSpacing: '0.0075em',
        textAlign: 'left',
    },
    subtitle1: {
        fontFamily: '"Roboto", "Helvetica", "Arial", sans-serif',
        fontWeight: 400,
        fontSize: '1rem',
        lineHeight: 1.75,
        letterSpacing: '0.00938em',
        textAlign: 'left',
    },
    subtitle2: {
        fontFamily: '"Roboto", "Helvetica", "Arial", sans-serif',
        fontWeight: 500,
        fontSize: '0.875rem',
        lineHeight: 1.57,
        letterSpacing: '0.00714em',
        textAlign: 'left',
    },
    body1: {
        fontFamily: '"Roboto", "Helvetica", "Arial", sans-serif',
        fontWeight: 400,
        fontSize: '1rem',
        lineHeight: 1.5,
        letterSpacing: '0.00938em',
        textAlign: 'left',
    },
    body2: {
        fontFamily: '"Roboto", "Helvetica", "Arial", sans-serif',
        fontWeight: 400,
        fontSize: '0.875rem',
        lineHeight: 1.43,
        letterSpacing: '0.01071em',
        textAlign: 'left',
    },
    button: {
        fontFamily: '"Roboto", "Helvetica", "Arial", sans-serif',
        fontWeight: 500,
        fontSize: '0.875rem',
        lineHeight: 1.75,
        letterSpacing: '0.02857em',
        textTransform: 'none',
        textAlign: 'left',
    },
    caption: {
        fontFamily: '"Roboto", "Helvetica", "Arial", sans-serif',
        fontWeight: 400,
        fontSize: '0.75rem',
        lineHeight: 1.66,
        letterSpacing: '0.03333em',
        textAlign: 'left',
    },
    overline: {
        fontFamily: '"Roboto", "Helvetica", "Arial", sans-serif',
        fontWeight: 400,
        fontSize: '0.75rem',
        lineHeight: 2.66,
        letterSpacing: '0.08333em',
        textTransform: 'uppercase',
        textAlign: 'left',
    },
};

export default typography;
